apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata: 
  name: my-dynamodb-table
spec:
  tableName: my-dynamodb-table
  attributeDefinitions:
    - attributeName: weather
      attributeType: S
  keySchema:
    - attributeName: weather
      keyType: HASH
  billingMode: PAY_PER_REQUEST
